[project]
name = "kofta"
version = "0.1.0"
description = "KOFTA: Option-aware Fuzzing with Taint Analysis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "pyqt5>=5.15.11",
]
